name: Cat Walks About the Gallery
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
            use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::tidyverse
            any::jsonlite
      - name: Art Pulls
        run: Rscript R/daily.R
      - name: Commit files
        run: |
          git config --local user.email "jacobmgreer@gmail.com"
          git config --local user.name "Jacob Greer"
          git add --all
          git commit -am "add data"
          git push
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 6
